### ISSUE TITLE
Error in ISOtoCountry

### ISSUE THREAD

**Issue by Dmirandae** [alarconvv/geocleaMT#4]
The code to check the iso value, always returns "Wrong ISO value". The code must be
 if all(iso != c(2,3)) {
    stop("Wrong ISO value")
  }

OR
 if (iso != 2 & iso != 3) {
    stop("Wrong ISO value")
  }

**Comment by alarconvv** [comment]
porfavor mandame la funcion corregida, y yo monto el archivo

---

Viviana Romero Alarcon
Est. Biología
Universidad Industrial de Santander

2016-01-26 9:28 GMT-05:00 Daniel R. Miranda-Esquivel <
notifications@github.com>:

**Comment by Dmirandae** [comment]
Done

**Comment by Dmirandae** [comment]
function updated
